POST http://localhost:3003/auth/register
Content-Type: application/json

{
    "username": "GoddessCarlie",
    "email": "1@carlie.com",
    "password": "iAmAwesome"
}

###

POST http://localhost:3003/auth/login
Content-Type: application/json

{
    "email": "carlie_is_cool@carlie.com",
    "password": "iAmAwesome"
}