GET http://localhost:3003/book/search
Content-Type: application/json

{
    "title": "The Name Of The Wind",
    "author": "Patrick Rothfuss"
}

###

GET http://localhost:3003/book/BcG2dVRXKukC

###

GET http://localhost:3003/error-testing