GET http://localhost:3003/u/search
Content-Type: application/json

{
    "username": "GoddessCarlie"
}

###

GET http://localhost:3003/u/5eaea561328f562b263a4930

###

PATCH http://localhost:3003/u/5eaea561328f562b263a4930
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1Zjc2ZGVkN2E3ODhjOTFjMzk5Mzg0MTAiLCJ1c2VybmFtZSI6IkdvZGRlc3NDYXJsaWUiLCJpYXQiOjE2MDE2MjU4MTUsImV4cCI6MTYwMTcxMjIxNSwic3ViIjoiNWY3NmRlZDdhNzg4YzkxYzM5OTM4NDEwIn0.-1SStAVirMLpLYlLdUzUFjtZRdvIGtxtrUKlsaLZdTc

{
    "username": "TestingCarlie"
}

###

DELETE http://localhost:3003/u/5eaea561328f562b263a4930
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1Zjc2ZGVkN2E3ODhjOTFjMzk5Mzg0MTAiLCJ1c2VybmFtZSI6IkdvZGRlc3NDYXJsaWUiLCJpYXQiOjE2MDE2MjU4MTUsImV4cCI6MTYwMTcxMjIxNSwic3ViIjoiNWY3NmRlZDdhNzg4YzkxYzM5OTM4NDEwIn0.-1SStAVirMLpLYlLdUzUFjtZRdvIGtxtrUKlsaLZdTc